title:            nobe4's blog
description:      :q! since 2012
created:          Built
url:              http://nobe4.fr

# Settings for reading time
reading_time:     true
words_per_minute: 200

# Owner/author information
owner:
  name:           nobe4
  bio:            I use Vim. Damn.
  disqus_name:    nobe4fr
  social:
    twitter:
      fa-icon:    fa-twitter
      username:   nobe_4
      url:        https://twitter.com/nobe_4
    github:
      fa-icon:    fa-github
      url:        https://github.com/nobe4
    stackexchange:
      fa-icon:    fa-stack-overflow
      url:        http://vi.stackexchange.com/users/1821/nobe4
    linkedin:
      fa-icon:    fa-linkedin
      url:        https://uk.linkedin.com/in/nobe4
    soundcloud:
      fa-icon:    fa-soundcloud
      url:        https://soundcloud.com/nobe4

google_analytics: 'UA-57774120-4'

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:       Europe/London
locale:         en_GB

# Edition
future:         true
highlighter:    rouge
markdown:       kramdown

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: ":num/"

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all

image:
  path: /assets/images/

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      category: "p"
      comments: true

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title/

include: [".htaccess", "_pages"]
exclude: ["LICENSE", "README.md", "LICENSE"]
