baseURL = 'https://nobe4.fr/'
languageCode = 'en-us'
title = "nobe4"
enableGitInfo = true

[taxonomies]
tag = "tags"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[module.hugoVersion]
min = "0.150.0"
