baseURL = 'https://nobe4.fr/'
languageCode = 'en-us'
title = "nobe4"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[module.hugoVersion]
extended = false
min = "0.116.0"
