baseURL = 'https://nobe4.fr/'
languageCode = 'en-us'
title = "nobe4"
enableGitInfo = true
copyright = '<a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a>'

[permalinks]
[permalinks.page]
posts = '/posts/:slug/'

[params]
[params.author]
name = "nobe4"

[taxonomies]
tag = "tags"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[module.hugoVersion]
min = "0.150.0"
